### ISSUE TITLE
Cannot use references in JSON query parameters

### ISSUE THREAD

**Issue by arminrosu** [IBM/openapi-to-graphql#309]
**Describe the bug**

I declared basic [RQL](https://github.com/a8m/rql) query parameters in the API, which are JSON. I wanted to use references to it, but the converter fails.

Embedding the referenced properties works marvelously.

References are very helpful in this case, because the `query.filter` object can then contain the endpoint schema properties.

**To Reproduce**

1. Copy this code in `test.yml`:

```yaml
openapi: "3.0.2"
info:
  title: TEST
  version: 1.0.0

paths:
  /tags:
    get:
      operationId: listTags
      parameters:
        - in: query
          name: query
          content:
            application/json:
              schema:
                type: object
                properties:
                  allOf:
                    # This will throw an error. Embedding properties doesn't
                    $ref: '#/components/schemas/RQLQuerySchema'
      responses:
        200:
          $ref: '#/components/responses/Tags'

components:
  responses:
    Tags:
      description: A list of Tags
      content:
        application/json:
          schema:
            properties:
              data:
                items:
                  $ref: '#/components/schemas/Tag'
                type: array
            type: object

  schemas:
    RQLQuerySchema:
      type: object
      properties:
        limit:
          example: 10
          format: int32
          type: integer
    Tag:
      type: object
      properties:
        id:
          format: uuid
          type: string
        label:
          type: string
```
2. Run `openapi-to-graphql test.yml --save test.graphql`
3. See error:
```bash
Cannot use 'in' operator to search for '#' in undefined
```

**Expected behavior**

Expected to resolve references.

**Additional context**

* `openapi-to-graphql-cli` version `2.0.0`

**Comment by Alan-Cha** [comment]
@pbmacg So sorry for the late reply. I've been buried under work since last week and I think I will continue to be blocked the rest of this week. I will try to take a brief look later today but I just wanted to let you know what is going on so I don't fail your expectations. Best of luck for the time being.

**Comment by arminrosu** [comment]
@Alan-Cha no worries, I completely understand. I would have looked deeper into a fix if I myself had a bit more time. Thanks :)

**Comment by michaeldharrington** [comment]
Also curious if this can be supported, @arminrosu did you happen to get anywhere? (I'm just experiencing now).

**Comment by arminrosu** [comment]
@michaeldharrington hmmm, I think I got it. The issue stems from `resolveRef` not getting the `oas` passed along, so it cannot find  the `RQLQuerySchema` reference in `undefined`.

I changed [these lines](https://github.com/IBM/openapi-to-graphql/blob/97e37f765de73908447d81566c33f95b07fe58f0/packages/openapi-to-graphql/src/schema_builder.ts#L1105):

```diff js
    // TODO: remove
    const paramDef = createDataDef(
      { fromSchema: parameter.name },
      schema as SchemaObject,
      true,
-      data
+      data,
+      undefined,
+      operation.oas
    )
```

@Alan-Cha what do you think? The `// TODO: remove` comment makes me wonder if you want a more comprehensive solution.

**Comment by Alan-Cha** [comment]
@arminrosu I think you found the bug! This is awesome! 

I think we should make the OAS a required parameter on `createDataDef`. The only reason why it is optional is we use the same function to create the `[viewer](https://github.com/IBM/openapi-to-graphql/tree/master/packages/openapi-to-graphql#options)` objects, which do not depend on the OAS. 

I put the `TODO` comment because I was wondering if we should do something simpler here. To my knowledge, [operation parameters](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#parameter-object) are generally simple key-value pairs. I was thinking that `createDataDef` might be too heavy duty and we could do something more streamlined. My opinion now is that we should stick with `createDataDef`. 

I'll make a PR. Thank you so much for looking into the problem when I couldn't!

**Comment by DR-Arvata** [comment]
Is the error that I'm getting here pointing to this 'bug' or am i running into something different?
 
`OpenAPI-to-GraphQL creation event error: Cannot use 'in' operator to search for '$ref' in undefined`

**Comment by uptownhr** [comment]
I'm also seeing the `$ref` in undefined error. But in my 60k line JSON file, it is almost impossible to find out what is triggering this.

**Comment by oddball** [comment]
I am also seeing 
```
TypeError: Cannot use 'in' operator to search for '$ref' in undefined
```

I did a validation of the yaml schema and it seems fine.

**Comment by arminrosu** [comment]
@oddball the yaml is definitely fine. I suggest denormalizing your yaml file first, by resolving all references. If you don't have `$ref`, you don't have errors 😅

**Comment by oddball** [comment]
@arminrosu, thanks, unsure of how I do that. May I trouble you for some instructions?! Am I so lucky there exist a command line tool for that?

**Comment by arminrosu** [comment]
@oddball I've give [swagger-parser](https://www.npmjs.com/package/swagger-parser) a shot, it has a [dereference method](https://apitools.dev/swagger-parser/docs/swagger-parser.html#dereferenceapi-options-callback).

**Comment by oddball** [comment]
@arminrosu Thanks! swagger-cli worked well. There are no $ref in the resulting yaml file. Expanded the file from 8k lines to 50k lines. However I still get the same error.

```bash
npm install -g @apidevtools/swagger-cli
swagger-cli bundle --dereference api.yaml -t yaml -o deref_api.yml
openapi-to-graphql deref_api.yml
(node:8523) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for '$ref' in undefined
    at Object.getResponseSchemaAndNames (/usr/local/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/oas_3_tools.js:562:20)
    at processOperation (/usr/local/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/preprocessor.js:54:96)
    at /usr/local/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/preprocessor.js:192:39
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/preprocessor.js:158:18
    at Array.forEach (<anonymous>)
    at Object.preprocessOas (/usr/local/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/preprocessor.js:118:10)
    at translateOpenAPIToGraphQL (/usr/local/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/index.js:148:33)
    at /usr/local/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/index.js:86:25
```

**Comment by arminrosu** [comment]
@oddball sorry, that's where my foo ends, without seeing your file. I suggest you split it up based on your paths and see where the ref error comes from. Might help converting it to json first and parsing that programatically.
