### ISSUE TITLE
json-ptr package v1.3.0 breaking OAS

### ISSUE THREAD

**Issue by johnmbarry-nhvr** [IBM/openapi-to-graphql#339]
TypeError: jsonptr.get is not a function at /src/oas_3_tools.ts:268:18

Perform clean install of latest version of openapi-to-graphql

Translate an openapi spec with references.

UnhandledPromiseRejectionWarning: TypeError: jsonptr.get is not a function
    at resolveRef (/node_modules/openapi-to-graphql/src/oas_3_tools.ts:268:18)
    at Object.getRequestSchemaAndNames (/node_modules/openapi-to-graphql/src/oas_3_tools.ts:625:23)
    at processOperation (/node_modules/openapi-to-graphql/src/preprocessor.ts:88:17)
    at /node_modules/openapi-to-graphql/src/preprocessor.ts:302:33
    at Array.forEach (<anonymous>)
    at /node_modules/openapi-to-graphql/src/preprocessor.ts:256:10
    at Array.forEach (<anonymous>)
    at Object.preprocessOas (/node_modules/openapi-to-graphql/src/preprocessor.ts:207:8)
    at translateOpenAPIToGraphQL (/node_modules/openapi-to-graphql/src/index.ts:260:61)
    at /node_modules/openapi-to-graphql/src/index.ts:172:11

**Comment by Alan-Cha** [comment]
@johnmbarry-nhvr Thanks for filling this issue. I believe we have a fix in the works #338. I'll try to get this accepted as soon as possible.

**Comment by Alan-Cha** [comment]
@johnmbarry-nhvr There does seem to be some issue around this library as seen [here](https://github.com/flitbit/json-ptr/issues/24). This issue should be, for the time being, addressed by #338 and the release of `v2.2.4`. However, depending on how the library will change in the future, more work may need to be done.
