### ISSUE TITLE
Cannot generate graphql schema with circular oneOf types due to infinite recursion

### ISSUE THREAD

**Issue by swatkatz** [IBM/openapi-to-graphql#355]
**Describe the bug**
Run:
openapi-to-graphql ~/person_schema.json --save person_schema.graphql

If the openapi schema has a oneOf field that refers to the containing type, the code says:
```
RangeError: Maximum call stack size exceeded
    at Object.sanitize (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/oas_3_tools.js:864:18)
    at createFields (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/schema_builder.js:396:48)
    at fields (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/schema_builder.js:121:24)
    at resolveThunk (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/graphql/type/definition.js:480:40)
    at defineFieldMap (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/graphql/type/definition.js:692:18)
    at GraphQLObjectType.getFields (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/graphql/type/definition.js:633:27)
    at /Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/schema_builder.js:232:44
    at Array.sort (<anonymous>)
    at checkAmbiguousMemberTypes (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/schema_builder.js:231:11)
    at createOrReuseUnion (/Users/swatikumar/.nvm/versions/node/v12.19.1/lib/node_modules/openapi-to-graphql-cli/node_modules/openapi-to-graphql/lib/schema_builder.js:192:9)
```

**To Reproduce**
For this schema:
```
{
    "openapi": "3.0.0",
    "servers": [
      {
        "url": "https://api.random.com/"
      }
    ],
    "info": {
        "description": "The Random REST API. Please see https://random.com/docs/api for more details.",
        "termsOfService": "https://random.com/us/terms/",
        "title": "Random API",
        "version": "foo-bar"
    },
    "paths": {
        "/v1/random/person/{id}": {
            "get": {
                "description": "Retrieves random person",
                "operationId": "GetRandomPersonId",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                          "type": "string"
                        },
                        "style": "simple"
                      }
                  ],
                  "responses": {
                    "200": {
                      "content": {
                        "application/json": {
                          "schema": {
                            "$ref": "#/components/schemas/person"
                          }
                        }
                      },
                      "description": "Successful response."
                    },
                    "default": {
                      "content": {
                        "application/json": {
                          "schema": {
                            "$ref": "#/components/schemas/error"
                          }
                        }
                      },
                      "description": "Error response."
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "person": {
                "description": "This is an object representing a person",
                "properties": {
                    "first_name": {
                        "description": "First name",
                        "nullable": true,
                        "type": "string"
                    },
                    "last_name": {
                        "description": "Last name",
                        "nullable": true,
                        "type": "string"
                    },
                    "siblings": {
                        "description": "A list of siblings of this person",
                        "items": {
                            "$ref": "#/components/schemas/person"
                          },
                        "nullable": false,
                        "type": "array"
                    },
                    "employer": {
                        "description": "The employer of this person",
                        "$ref": "#/components/schemas/employer"
                    },
                    "parent": {
                      "nullable": true,
                      "oneOf": [
                        {
                          "$ref": "#/components/schemas/employer"
                        },
                        {
                          "$ref": "#/components/schemas/person"
                        }
                      ]
                    }
                },
                "required": [
                    "employer",
                    "siblings"
                ]
            },
            "employer": {
                "description": "This is an object representing an employer",
                "properties": {
                    "name": {
                        "description": "Employer name",
                        "nullable": true,
                        "type": "string"
                    },
                    "year_founded": {
                        "description": "Founding year",
                        "nullable": true,
                        "type": "integer"
                    },
                    "employees": {
                        "description": "The employees of this employer",
                        "items": {
                            "$ref": "#/components/schemas/person"
                        },
                        "type": "array"
                    },
                    "employer": {
                        "description": "Parent company",
                        "$ref": "#/components/schemas/employer"
                    }
                },
                "required": [
                    "employees",
                    "parent_company"
                ]
            },
            "error": {
                "description": "An error response from the API",
                "properties": {
                    "code": {
                        "description": "For some errors that could be handled programmatically, a short string indicating the error",
                        "maxLength": 5000,
                        "type": "string"
                    }
                },
                "required": [
                  "error"
                ],
                "type": "object"
            }
        }
    }
}
```

The issue occurs when the `parent` field refers back to `person` in the `oneOf`. Note that things work fine for objects and lists.

In looking at the code, the issue is inside the `checkAmbiguousMemberTypes ` at this [line](https://github.com/IBM/openapi-to-graphql/blob/a6db048a6d062342554c780694f4b4d99f3d221c/packages/openapi-to-graphql/src/schema_builder.ts#L369)
Since the `fields` haven't been processed, it calls the same stack to process the fields again and goes into infinite recursion.

**Expected behavior**
Expect the schema generation to work and a Graphql schema to be output. The schema generation works fine if that function is commented out

**Comment by Alan-Cha** [comment]
Thanks for also taking a look at the code! There are definitely some still some issues with resolving these JSON combine schema keywords. I am going to see if I can find some time to take a look at this as well as other issues during the next week.

**Comment by swatkatz** [comment]
Awesome, that sounds great. Thanks for the quick response!

**Comment by mmmveggies** [comment]
Any movement on this? I believe something similar is happening with the following:
```
npx openapi-to-graphql-cli https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json
```
yielding:
```
OpenAPI-to-GraphQL creation event error: Maximum call stack size exceeded
```

however, this is fixed by removing the `oneOf` definitions from this schema.

**Comment by Alan-Cha** [comment]
@mmmveggies Sorry, I haven't had the time to look at this at all. I plan to at some point but I keep hitting roadblocks.
